### PR TITLE
Migrated to new project structure

### PR DESCRIPTION
**Pull request by linux-china**
- Adopt IntelliJ Platform Plugin Template structure
- LineMark icon for main function: run main method from mark icon
- LineMark icon for test functions: run Zig tests from test mark icon
- Compatible with 203 - 2022.2

### CODE REVIEW

**Review by ice1000 — COMMENTED** [review]
If you want to change the project structure this much, I'd rather kindly ask you to maintain your own project and ask me to add a link to your project.

This is like an entire rewrite. Some files I don't like are committed, like `.run` directory, and my carefully written `build.gradle.kts`. I believe most of these files won't need to be changed.

**Comment by linux-china** [comment]
It's not to rewrite.  Now most JetBrains plugins are to follow official template:  https://github.com/JetBrains/intellij-platform-plugin-template ,  and I just moved code into template's different directories.   Most plugin developers know this template structure very well, and it's easy for other plugin developers to contribute code.

**Comment by ice1000** [comment]
> It's not to rewrite.  Now most JetBrains plugins are to follow official template:  https://github.com/JetBrains/intellij-platform-plugin-template ,  and I just moved code into template's different directories.   Most plugin developers know this template structure very well, and it's easy for other plugin developers to contribute code. 

Yes, I'm okay with moving files. It's just that I don't like putting local IDE configurations to GitHub. You also changed my build script. I think you misunderstood me.

**Comment by ice1000** [comment]
Also, I'm extremely busy lately. You may expect instant replies on GitHub, but I barely have time to touch a computer

**Comment by ice1000** [comment]
image

This is making your contribution very hard to review.

**Comment by linux-china** [comment]
I closed this PR first. If you think new project structure  is good, and you can do migration first, then I create new PR based on new project  structure.

**Comment by ice1000** [comment]
> I closed this PR first. If you think new project structure is good, and you can do migration first, then I create new PR based on new project structure.

Sure

**Pull request closed without merging**
