### PR TITLE
Plugin sources reformatting & updating to the latest IDEA plugin API

### PR DESCRIPTION
**Pull request by anatol**

### CODE REVIEW

**Review by ice1000 — COMMENTED** [review]
Could you please do not change indentation?

It's making the PR insanely hard to review.

**Comment by ice1000** [comment]
image

These commits are great!

**Comment by ice1000** [comment]
I checked them. Exactly what I was waiting for. Moved...

**Comment by anatol** [comment]
The reformatting patch is to address code inconsistency. It is an automatic one done by Intellij's "Reformat code" action.

I was using the default IDEA code style settings. Do you propose to use some non-default style instead? In this case the style settings should be stored in the project source-tree.

**Comment by ice1000** [comment]
> I was using the default IDEA code style settings. Do you propose to use some non-default style instead?

Oooh. Yes, I propose using tabs. Reasons:

+ When this project is developed, Kotlin has no official style. So I used tabs.
+ If you reformat it, all bugs I wrote will be shown as "authored by you" in git blame.

**Comment by ice1000** [comment]
Unfortunately, I do not have the old code style settings anymore. Is it feasible for you to apply a change like this?

image

For the others, feel free to reformat. It's just the indentation makes the code review very difficult (I can't see your changes without looking at 2000+ loc trivial reformats)

**Comment by ice1000** [comment]
I wish I'm not spoiling your interests on reviving this project...

**Comment by anatol** [comment]
I can drop the reformatting patch to make reviewing other patches easier.

But eventually, the formatting needs to be clarified. I still think using default IDEA settings is probably the cleanest option.

I do not mind if you do the mass reformatting on your side so the git history will stay clear.

**Comment by ice1000** [comment]
> But eventually, the formatting needs to be clarified. I still think using default IDEA settings is probably the cleanest option.

I will upload an editorconfig file later.

**Comment by ice1000** [comment]
Ok, I have a new idea now

**Comment by ice1000** [comment]
Try this:

Give me two PRs. One is the reformat. One is the other changes. Deal?

**Comment by ice1000** [comment]
You kinda convinced me that using the official code style is better. We should expect other contributors who share the same philosophical belief.

**Comment by anatol** [comment]
> You kinda convinced me that using the official code style is better. We should expect other contributors who share the same philosophical belief.

Yeah, it's just a matter of saving contributors time figuring out formatting. I found that forcing everyone to use standard default formatting is more efficient than having inconsistent code and no formatting.

Anyway, let me know how you prefer to deal with these patches. I can drop the reformatting part. It will take a bit of time for me to rebase the changes.

**Comment by ice1000** [comment]
> Anyway, let me know how you prefer to deal with these patches. I can drop the reformatting part. It will take a bit of time for me to rebase the changes.

Did you see my replies? https://github.com/ice1000/intellij-zig/pull/40#issuecomment-1289393466

**Comment by ice1000** [comment]
Hello? @anatol

**Comment by anatol** [comment]
Sure, so I dropped the automatic reformatting from my PR list. now the set of changes is much smaller.

PTAL.

**Comment by anatol** [comment]
Thanks a lot.

Do you want to proceed with the reformatting patch? Do you plan to do it yourself?

**Comment by anatol** [comment]
I also want to change the project structure a bit and apply recommendations from the IntelliJ plugin template project https://github.com/JetBrains/intellij-platform-plugin-template

what do you think?

**Comment by ice1000** [comment]
> I also want to change the project structure a bit and apply recommendations from the IntelliJ plugin template project https://github.com/JetBrains/intellij-platform-plugin-template
> 
> what do you think?

I don't like it. I like the flat structure.

**Comment by ice1000** [comment]
> Thanks a lot.
> 
> Do you want to proceed with the reformatting patch? Do you plan to do it yourself?

You go ahead. :)

**Pull request merged**
